### ISSUE TITLE
[FE]Profile_Education:Vertical scroll bar appearance does not meet UI mockup requirements in the Education tab

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#439]
Preconditions:
1. Open web application;
2. Login;
3. Navigate to Profile;
4. Go to Education;
5. Click '+' button.

STR:
1. Add 5 education records/add until appearing the vertical scroll bar
7. Pay attention on the view of the vertical scroll bar

AR:
The view of the vertical scroll bar is not met UI mockup requirements.
look attachment

 
ER:
The view of the vertical scroll bar should be met [UI mockup requirements ](https://www.figma.com/design/0CyiTbfkKhc6ab5jD8g61w/core_ver2?node-id=1504-12910&t=Pq25zUqtJxWs6P8Y-4)

Attachment:
![Image](https://github.com/ratifire/devrate-web/assets/172209912/0313d15c-39bb-4351-8d73-c766b1403827)

**Comment by KhanAnna** [comment]
![Image](https://github.com/user-attachments/assets/37e7d2cc-a847-4de2-acfb-4fcca008ebb5)
