### ISSUE TITLE
Bug report: Registration with one letter and one space in the name

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#444]
The system registers a user with such a name, but the site crashes afterward. The login button disappears and is replaced by a profile button, which, when clicked, causes the site to display errors and a window with a button to go back to the homepage. Registering again with valid data resolves this issue.

![Image](https://github.com/ratifire/devrate-web/assets/160535741/1e60b0fd-fb37-489b-8282-794f4ea9312a)
![Image](https://github.com/ratifire/devrate-web/assets/160535741/33f19fdd-5f85-4404-899c-6991e9694b43)
![Image](https://github.com/ratifire/devrate-web/assets/160535741/5eaad5b6-05e1-4d60-8887-cfefdf268fe6)

**Comment by DmitroLis** [comment]
The Bug was fixed
