### ISSUE TITLE
[FE]Login: A validation error message is shown when entering an email address with '+N' in the local part.

### ISSUE THREAD

**Issue by vasi-pm** [ratifire/devrate-web#635]
**Preconditions:**

1. Complete registration with a valid email 'test+1@gmail.com' / with an additional value '+1'.

**STR:**

1. Open the application.
2. Go to the login page.
3. Enter the valid email used during registration, e.g., 'test+1@gmail.com'.
4. Move out of focus from the email input field.

**AR:** 
A validation error message is shown when entering an email address with an additional value in the local part.

**ER:** 
The user should be able to enter an email address with an additional value in the local part.

**Attachment:**
![Image](https://github.com/user-attachments/assets/3aa1a596-8906-47e6-b7a3-9a6ddcf6b708)

**Comment by vplabunets** [comment]
We don't need to have possibility to add "+" and other specific signs.
For example in GMAIL:
Usernames cannot contain ampersands (&), equal signs (=), underscores (_), apostrophes ('), hyphens (-), plus signs (+), commas (,), brackets (<,>), or several periods (.) in a row.

**Comment by vasi-pm** [comment]
This issue is fixed.
