### ISSUE TITLE
[FE] My_profile: the animation when clicking the arrow when returning to step 1 is different from the other buttons / анімація під час натискання стрілки під час повернення до кроку 1 відрізняється від інших кнопок (к-61)

### ISSUE THREAD

**Issue by KhanAnna** [ratifire/devrate-web#638]
In the first video, it is visible that the circular animation is missing.
In the second video, the animation is present, but it does not reach the button's border as it does with other similar buttons.

https://github.com/user-attachments/assets/55190719-bfdb-4516-9f9d-15a670f627a5

https://github.com/user-attachments/assets/5376e3e8-ddc1-4624-9ddc-7d8fb63676b0

**Comment by VladyslavDykyi** [comment]
так, де відрізняеться якщо, кнопка блокуеться бо це останній слайд і неможна на неї натиснути

**Comment by vplabunets** [comment]
@KhanAnna Що саме не так як має бути? І як має бути?

**Comment by KhanAnna** [comment]
I'm not sure how critical this is, but when returning to step 1 (personal information), the button animation (the ripple effect) is missing.

Я не знаю, наскільки це критично, але під час повернення до кроку 1 (особиста інформація) анімація кнопки (ефект хвилі) відсутня.

**Comment by VladimirShaitan** [comment]
@KhanAnna Привіт, анімація на кнопці є, для того щоб перевірити треба при переході на перший степ, затиснути кнопку.
Після того як відпустиш кнопку кнопка перейде в стан **disabled**
