### ISSUE TITLE
[FE] My_profile  Contact Information: after filling in any field in the "Contact Information" and pressing the save button, the form closes / після заповнення будь-якого поля в «Контактній інформації» і натискання кнопки збереження форма закривається (К-64)

### ISSUE THREAD

**Issue by KhanAnna** [ratifire/devrate-web#640]
AR: after filling in any field in the "Contact Information" and pressing the save button, the form closes

ER: after filling in any field in the "Contact Information" and pressing the save button, the form does not close, you can continue to interact with it or move to other sections

https://drive.google.com/file/d/1g9vW10q4F7WuhFMwouN3CKep635qTjKB/view?usp=sharing

**Comment by KhanAnna** [comment]
https://github.com/user-attachments/assets/2434807c-5476-4434-8c6c-49c58ef3c8da
reopen

**Comment by VladimirShaitan** [comment]
@KhanAnna Привіт, в нас тут тікети котрі виключають один одного, будь ласка, проясни як саме повинно бути зроблено
Поки цей тікет заблоканий 

Посилання на виключення тікету - https://github.com/orgs/ratifire/projects/9/views/1?pane=issue&itemId=84078588&issue=ratifire%7Cdevrate-web%7C815
