### ISSUE TITLE
[FE] Achievements. The "Save" button doesn't work with valid data.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#662]
The "Save" button

https://github.com/user-attachments/assets/01d8d069-7424-4ed7-888b-7c59547223ac

 doesn't work when you enter valid data.

**Comment by SamZakharov** [comment]
@DmitroLis 
Can you double-check this error? This tab's functionality now differs from what is in the video.

**Comment by SamZakharov** [comment]
This bug is not reproducible.
