### ISSUE TITLE
[FE] [Calendar] Intervirews are not visible when calendar just opened.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#775]
When calendar just opened, FE makes request to BE with wrong date range:
https://server.devrate.org/users/2/events?from=2024-10-08&to=2024-10-07 and gets in response "[]"
That's why scheduled interviews are not displayed when calendar just opened.

![Image](https://github.com/user-attachments/assets/abc5db31-b053-41a7-a89c-02338c6559a1)

**Comment by vplabunets** [comment]
Hi. Could you please, retest current bug. Seems, that it was solved.
