### ISSUE TITLE
Create white theme on personal profile page

### ISSUE THREAD

**Issue by VladimirShaitan** [ratifire/devrate-web#780]
Створити конфігурацію світлої теми для строніки персонального профілю користувача.

В цю задачу входить зміна компонентів, для імплементації теми.

**Comment by SamZakharov** [comment]
https://www.figma.com/design/0CyiTbfkKhc6ab5jD8g61w/core_ver2?node-id=7694-33502&node-type=frame&t=yF7r3sAu0PEw1kYf-0
