### ISSUE TITLE
[FE] [registration] the user's email address is not masked in the verification code entry window (A)

### ISSUE THREAD

**Issue by KhanAnna** [ratifire/devrate-web#790]
Actual results: the user's email is not hidden by symbols "*"
 
Expected results: the user's email is hidden by symbols "*"
![Image](https://github.com/user-attachments/assets/7205a8cf-05ab-47e2-b146-6800b50551d1)

as implemented on the password reset window
![Image](https://github.com/user-attachments/assets/f6a9ce66-c97a-4695-bab8-28c8ffacb0b9)

**Comment by vplabunets** [comment]
@KhanAnna Could you please, test again. I can see hidden email. 
![image](https://github.com/user-attachments/assets/b540ba3f-e7f6-4f2a-a823-7d4cc1d89101)

**Comment by KhanAnna** [comment]
баг присутній у вікні введення коду підтвердження після заповнення форми реєстрації. (на вашому фото форма введення коду підтвердження під час скидання пароля)

The bug is present in the confirmation code entry window after completing the registration form. (Your screenshot shows the confirmation code entry form for password reset.)

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c3e1c6fa-5ad1-4589-9287-f3261b6c3690">
