### ISSUE TITLE
[FE] Registration. Space in Email field.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#795]
A space cannot be used in the email field

![Image](https://github.com/user-attachments/assets/49f78d93-ad50-46ad-8185-a4c1f183d869)

**Comment by VladimirShaitan** [comment]
@DmitroLis там дизайнери готують новий дизайн аутентифікаційних модалок, тому не має сенсу зараз це фіксити

**Comment by VladimirShaitan** [comment]
@BhdnS Можна брати

**Comment by DmitroLis** [comment]
The Bug was fixed
