### ISSUE TITLE
[FE] The list of countries is not complete.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#796]
Our country list has only 34 countries 
Here is a complete list of countries excluding rashka

Afghanistan  
Albania  
Algeria  
Andorra  
Angola  
Antigua and Barbuda  
Argentina  
Armenia  
Australia  
Austria  
Azerbaijan  
Bahamas  
Bahrain  
Bangladesh  
Barbados  
Belarus  
Belgium  
Belize  
Benin  
Bhutan  
Bolivia  
Bosnia and Herzegovina  
Botswana  
Brazil  
Brunei  
Bulgaria  
Burkina Faso  
Burundi  
Cabo Verde (Cape Verde)  
Cambodia  
Cameroon  
Canada  
Central African Republic  
Chad  
Chile  
China  
Colombia  
Comoros  
Congo, Democratic Republic of the  
Congo, Republic of the  
Costa Rica  
Croatia  
Cuba  
Cyprus  
Czech Republic (Czechia)  
Denmark  
Djibouti  
Dominica  
Dominican Republic  
East Timor (Timor-Leste)  
Ecuador  
Egypt  
El Salvador  
Equatorial Guinea  
Eritrea  
Estonia  
Eswatini (Swaziland)  
Ethiopia  
Fiji  
Finland  
France  
Gabon  
Gambia  
Georgia  
Germany  
Ghana  
Greece  
Grenada  
Guatemala  
Guinea  
Guinea-Bissau  
Guyana  
Haiti  
Honduras  
Hungary  
Iceland  
India  
Indonesia  
Iran  
Iraq  
Ireland  
Israel  
Italy  
Ivory Coast (Côte d'Ivoire)  
Jamaica  
Japan  
Jordan  
Kazakhstan  
Kenya  
Kiribati  
Korea, North (North Korea)  
Korea, South (South Korea)  
Kosovo  
Kuwait  
Kyrgyzstan  
Laos  
Latvia  
Lebanon  
Lesotho  
Liberia  
Libya  
Liechtenstein  
Lithuania  
Luxembourg  
Madagascar  
Malawi  
Malaysia  
Maldives  
Mali  
Malta  
Marshall Islands  
Mauritania  
Mauritius  
Mexico  
Micronesia  
Moldova  
Monaco  
Mongolia  
Montenegro  
Morocco  
Mozambique  
Myanmar (Burma)  
Namibia  
Nauru  
Nepal  
Netherlands  
New Zealand  
Nicaragua  
Niger  
Nigeria  
North Macedonia  
Norway  
Oman  
Pakistan  
Palau  
Panama  
Papua New Guinea  
Paraguay  
Peru  
Philippines  
Poland  
Portugal  
Qatar  
Romania  
Rwanda  
Saint Kitts and Nevis  
Saint Lucia  
Saint Vincent and the Grenadines  
Samoa  
San Marino  
São Tomé and Príncipe  
Saudi Arabia  
Senegal  
Serbia  
Seychelles  
Sierra Leone  
Singapore  
Slovakia  
Slovenia  
Solomon Islands  
Somalia  
South Africa  
South Sudan  
Spain  
Sri Lanka  
Sudan  
Suriname  
Sweden  
Switzerland  
Syria  
Taiwan  
Tajikistan  
Tanzania  
Thailand  
Togo  
Tonga  
Trinidad and Tobago  
Tunisia  
Turkey  
Turkmenistan  
Tuvalu  
Uganda  
Ukraine  
United Arab Emirates  
United Kingdom  
United States  
Uruguay  
Uzbekistan  
Vanuatu  
Vatican City (Holy See)  
Venezuela  
Vietnam  
Yemen  
Zambia  
Zimbabwe

**Comment by BlackPuma9** [comment]
Hi @DmitroLis 

Could you please describe in more details in which part of interphase bug was identified?

Since I see on log in page, profile page = 116 countries

![Image](https://github.com/user-attachments/assets/66e91966-e58e-4d9e-bce0-d3e76b48ce14)

Agree that some part of countries missing, back-end team will add it soon to src/main/resources/static/data/user/countries.json soon.

Thanks in advanced!

Kind regards,

Yuliia

**Comment by DmitroLis** [comment]
Добрий день просто відкрив список країн та перерахував їх, було 34 країни
Коли додадуть всі тоді і бага закриється

**Comment by BlackPuma9** [comment]
@DmitroLis Hi hi
Backend team updated list of countries
<img width="1293" alt="Screenshot 2024-10-21 at 17 30 05" src="https://github.com/user-attachments/assets/84aec5ca-1f83-4b03-8a98-aaa80b11f773">
Before testing please make sure that backed updated to the last version.
Yuliia

**Comment by DmitroLis** [comment]
The Bug was fixed
