### ISSUE TITLE
[FE] The checkbox "Send me news, surveys, and special offers from DEVRATE" should not affect the activity of the "Sign Up" button.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#800]
The checkbox "Send me news, surveys, and special offers from DEVRATE" should not affect the activity of the "Sign Up" button. 

https://github.com/user-attachments/assets/fa1677d2-624c-4558-8046-6ff749eec46d

**Comment by DmitroLis** [comment]
Добрий вечір @vplabunets, ви щось виправили із чек боксом? Бо досі не працює.

https://github.com/user-attachments/assets/860394fd-37b3-411c-9da1-914936f775b9

**Comment by DmitroLis** [comment]
@vplabunets Чи чекаємо нову модалку вів дизайнерів?

**Comment by vplabunets** [comment]
@DmitroLis зміни по чекбокусу вненсені. Очікують рев'ю від колег.
Не чув про зміни дизайну модалок. Дизайн змінюється на лендінг.

**Comment by DmitroLis** [comment]
Bug was fixed
