### ISSUE TITLE
[FE] Personal information. Incorrect work the "Save" button on "Contact information" field.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#815]
The "Save" button in the "Contact information" field closes this window. In other "Personal Information" windows, this button does not do this.

https://github.com/user-attachments/assets/38761872-9971-4fe0-945a-cfd57b5a06fe

**Comment by VladimirShaitan** [comment]
@DmitroLis Який очікуваний результат роботи, опиши будь ласка

**Comment by DmitroLis** [comment]
@VladimirShaitan Якщо подивитись відео, то видно що тільки в цьому вікні (Contact Information)
![Screenshot_1](https://github.com/user-attachments/assets/0fffcd4b-38d3-4ec2-97b8-d5b9c745e529)
 кнопка "SAVE" зачиняє вікно, усі інші кнопки "SAVE"
![1](https://github.com/user-attachments/assets/b9d9fe3c-b085-49b1-85f9-6fdc023c0f68)
![3](https://github.com/user-attachments/assets/82ea32e2-223c-4e94-8580-7b1676f05165)
![4](https://github.com/user-attachments/assets/202b992f-885e-40ed-b238-658290ff5b7f)
 у розділі "Personal Information", просто зберігають інформацію, а вікно не зачиняють. 

Очікуваний результат що все буде працювати однаково)), тобто або всі кнопки будуть зберігати інформацію і зачиняти вікно, або всі будуть просто зберігати інформацію.

**Comment by VladimirShaitan** [comment]
@DmitroLis Дякую, тепер зрозуміло

**Comment by DmitroLis** [comment]
Бага із різним поводженням кнопок "Save" все ще існує

https://github.com/user-attachments/assets/d5fb443f-f97b-4fc3-be38-e7adab9b8fb0
