### ISSUE TITLE
[FE] [Calendar] Unable to cancel interview via "Cancel Event" button in the time grid pop-up.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#830]
Description:
When cancelling a scheduled interview through the pop-up window in the time grid, clicking "Cancel Event" shows a temporary message. "Event not deleted due to problems." The interview is still on the calendar.

Steps to reproduce:
1. Open the Schedule page.
2. Click on the timeslot with the scheduled interview in the time grid.
3. In the pop-up, click the Cancel Event button.
 
Expected result:
Cancel the interview  from the schedule.

Actual result:
A message "Event was not deleted due to some problems" appears, and the  interview is still in the calendar.

Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 11

https://github.com/user-attachments/assets/9b9f23f2-af7f-4397-b49b-b2276cb754b3

**Comment by BhdnS** [comment]
Это моковые данные, с ними не будет работать удаление.
