### ISSUE TITLE
[FE] [Profile] Text appears grey instead of black in profile section with white theme.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#857]
Description: in the profile section, when using the light theme, the text is displayed in gray (#C5C5C6) instead of black (#1D1D1D), affecting readability and overall appearance.

Steps to reproduce:

1. Open the Profile page.
2.  Switch to the light theme.
3. Fully complete the profile.
4. Navigate to the profile section.

Expected result: the text "Congratulations! Your profile is completely filled out
in the profile section"  should be displayed in black.
![Image](https://github.com/user-attachments/assets/85b6de7b-a1bb-40ef-807d-13ccd827b95b)

Actual result: the text "Congratulations! Your profile is completely filled out
in the profile section" is gray.
![Image](https://github.com/user-attachments/assets/c3f4dd0a-f621-463a-9a08-6083cd493070)

Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 11

**Comment by SamZakharov** [comment]
Hi! I corrected it here, please check again

**Comment by OksanaTrokoz** [comment]
Everything looks correct
![Image](https://github.com/user-attachments/assets/7379c5a0-27b3-48f5-9906-93d1c8835cb4)
