### ISSUE TITLE
[Profile Contact Information] Gets an error when user paste link to the git account.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#878]
Steps:

Go to https://devrate.org/profile
Click on Edit Contact Information button
Paste "https://github.com/orgs/ratifire" to the GitHub field

Expected result:
System accepts URL

Actual result:
User gets an error "Please enter correct URL"

![Image](https://github.com/user-attachments/assets/9874e671-de4c-4fc8-bf4b-f2be58d29a88)

**Comment by SamZakharov** [comment]
Здравствуйте!
Попытался воспроизвести этот баг, но не вышло, прикладываю видео скрининг с сайта. Всё работаетhttps://github.com/user-attachments/assets/cc81327e-73f6-4307-bd7f-6424950347ea

**Comment by DmitroLis** [comment]
The Bug was fixed
