### ISSUE TITLE
[FE] [Specialisations] Downward arrow for the dropdown list in the Specialization name field is not visible in the white theme.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#882]
Precondition: User is registered and has switched to the white theme.

Steps to reproduce:

1. Log into the account.
2. Navigate to the Specialisations page.
3. Click the "+" button to add a new specialization.
4. In the opened Specialization pop-up, check the Specialisation name field.

Expected result: A downward arrow should be visible in the Specialization name field to open the dropdown list.
![Image](https://github.com/user-attachments/assets/bf1a84a7-c6e2-4a02-8712-e54ec0f0ed1f)

Actual result: The downward arrow is not visible in the white theme, making it impossible to open the dropdown list.
![Image](https://github.com/user-attachments/assets/a16a7a34-06e2-4375-af75-80a09d971d41)

**Comment by OksanaTrokoz** [comment]
![Image](https://github.com/user-attachments/assets/33624d7d-c67c-4949-af3f-874af3f6d691)
