### ISSUE TITLE
[FE] Personal information. Wrong error message.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#950]
**Bug Summary**
Error messages are unclear.

**Steps to Reproduce**
Register;
Log in to your profile;
Click on the edit personal information button;
Enter incorrect characters in the first and last name field to receive an error message (numbers, special characters);

**Expected Result**
"Invalid character" or "Only uppercase and lowercase letters allowed".

**Actual Result**
![Image](https://github.com/user-attachments/assets/605d753e-1eff-48ca-a1b9-f94ffa0d4486)

**Environment**
Google Chrome Версія 130.0.6723.70 (Офіційне складання) (64-розрядна версія)
Microsoft Windows [Version 10.0.19045.5011]

**Comment by VladimirShaitan** [comment]
@DmitroLis Дякую

**Comment by DmitroLis** [comment]
Бага все ще існує 

![Inv err mess1](https://github.com/user-attachments/assets/408c703f-ac13-4d12-94cb-9410536051df)

![Inv err mess bl ](https://github.com/user-attachments/assets/6fe01313-1571-4d6b-9e76-30de2b52e86c)

**Comment by DmitroLis** [comment]
The Bug was fixed
