### ISSUE TITLE
[FE] [Specialization] Wrong name Specialization on the tab "Specialization".

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#951]
Bug Summary:
Wrong name Specialization on the tab "Specialization".

Precondition:
User was previously registered.

Steps to reproduce:

1. Go to URL.
2. Log in.
3. Press the profile button on the top panel.
4. In the drop-down menu, select the ""Specialization"" tab.

Expected result: Correct name Specialization on the tab "Specialization".

Actual result: On the tab "Specialization" the title is displayed as "Specialisations".

Envinroment:
Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 10

![Image](https://github.com/user-attachments/assets/c112a846-0d63-4a3d-be05-1d5b008d1631)

**Comment by IrinaTonkonozhenko** [comment]
Verified
