### ISSUE TITLE
[FE] [Calendar] Redirects to participant profile with option to send message to oneself when clicking on own name in Schedule.

### ISSUE THREAD

**Issue by DmitroLis** [ratifire/devrate-web#952]
Precondition: an interview is scheduled with the user as a participant.

Steps to reproduce:
1. Open the "Schedule" page.
2. In the list below the calendar or in the time slot pop-up, find your own name (as an interview participant) and click on it.

Expected result: redirects to the user's personal profile page.
Actual result: redirects to the participant profile with an option to send a message to oneself.

Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 11
![Image](https://github.com/user-attachments/assets/b973392b-a2f0-4254-9fc8-d4750a192457)

**Comment by VladimirShaitan** [comment]
Пофіксити надпис на кнопці відправки повідомлення на чужому профайлі 
Повинно бути 'Write a message'

**Comment by VladimirShaitan** [comment]
@VladyslavDykyi Привіт 
Треба видалити те що ти написав і реалізувати цю логіку на рівні роутеру, нижче скину приклад як би я зробив щось подібне (псевдо код )

Створюємо компонент для захисту роуту цієї сторінки, приклад 
```js
import React from 'react';
import { Route, Navigate } from 'react-router-dom';

const ProtectedRoute = ({ element: Component, isAuthenticated, ...rest }) => {
  return (
    <Route
      {...rest}
      element={isAuthenticated ? <Component /> : <Navigate to="/login" replace />}
    />
  );
};

export default ProtectedRoute;
```

Далі в налаштуваннях роутеру робиш щось таке
```js
import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import ProtectedRoute from './ProtectedRoute';
import HomePage from './HomePage';
import Dashboard from './Dashboard';
import LoginPage from './LoginPage';

const App = () => {
  const isAuthenticated = // логика определения статуса авторизации

  return (
    <Router>
      <Routes>
        <Route path="/login" element={<LoginPage />} />
        <Route path="/" element={<HomePage />} />
        <ProtectedRoute path="/dashboard" element={Dashboard} isAuthenticated={isAuthenticated} />
      </Routes>
    </Router>
  );
};

export default App;
```

Це тільки приклад
Компонент повинен бути звязаний лиш з твоєю сторінкою 
і на базі перевіреного ід редіректити на сторінку юзера чи на сторінку свою

**Comment by BlackPuma9** [comment]
> Пофіксити надпис на кнопці відправки повідомлення на чужому профайлі Повинно бути 'Write a message'

Done in pull request https://github.com/ratifire/devrate-web/pull/981

**Comment by DmitroLis** [comment]
@OksanaTrokoz Привіт, перевір будь ласка свій Баг, як на мене він вже виправлений.

**Comment by OksanaTrokoz** [comment]
@DmitroLis Привіт,  поки що без змін.
