### ISSUE TITLE
[FE]Registration:  No error message when entering an invalid verification code in the "Confirm your email" window (№ K-16)

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#954]
Steps to reproduce

"1. Navigate to the URL.
2. Click the "registration" button.
3. Fill in all the fields and check all the boxes.
4. Click the "sign up" button.
5. Enter an incorrect verification code.
6. Click the registration button

Actual results.
after sending an invalid code, the form resets all data

 
Expected results
got an error "invalid code"

after talking with the designers (27.06.), decided that the only error that can occur when entering incorrect or long-generated code is "invalid code"

https://github.com/ratifire/devrate-web/assets/172079742/5eb24d36-f432-48cf-a81b-5e7d1b76fee2

**Comment by BlackPuma9** [comment]
Hi @KhanAnna,

Hope you are doing well!

![Image](https://github.com/user-attachments/assets/627081b3-1710-4c65-9c65-9c6d5f74198d)

I have verified the mentioned behavior in this bug and can confirm that it has been resolved. I have attached a ss showing the error message that is visible to the user when user entered incorrect code.

Let me know if you would like to adjust it.

Thank you!

Yuliia

**Comment by drozdovkostya** [comment]
Verified
