### ISSUE TITLE
Bug report: Registration with an existing Email

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#955]
When registering in the system with an existing email, the system displays a confirmation popup requesting a code, but nothing is sent to the email.

![Image](https://github.com/ratifire/devrate-web/assets/160535741/8497a2a2-3ec8-4e39-bdb0-39a07df59dbb)

**Comment by RuslanSoroka** [comment]
Привіт, на mailhog данні з кліенту приходять але щоб на пошту індівідуально призодило це треба на бекенді подивитися та налагодити.

**Comment by IvashchenkoIvanIgorevich** [comment]
@RuslanSoroka should implement error handling for existing email registration.

We will implement a new process for the email confirmation popup after adding Cognito. https://github.com/ratifire/devrate-service/issues/614

**Comment by DmitroLis** [comment]
The Bug still exist 

https://github.com/user-attachments/assets/22fd48b6-8ab4-4d4c-9952-7b100f4bff8b

**Comment by RuslanSoroka** [comment]
@DmitroLis hey, l suppose it because you use the “main” branch, while changes still in “develop” branch. Please try to switch to “develop” branch and check another one time.

**Comment by DmitroLis** [comment]
The bug was fixed
