### ISSUE TITLE
Поправити секцію FAQ на лендінгу skillzy

### ISSUE THREAD

**Issue by VladimirShaitan** [ratifire/devrate-web#965]
https://devrate.org/

Будь ласка, потестуй як вона працює і приведи того як намальовано в макеті

[Макет](https://www.figma.com/design/0CyiTbfkKhc6ab5jD8g61w/Skillzzy_ver2?node-id=10101-18720&node-type=canvas&t=I5P6W0Q5oNPh7Svt-0)

![Image](https://github.com/user-attachments/assets/6e9c6f7b-4463-4283-bed2-83c36273a56b)

**Comment by RuslanSoroka** [comment]
There was problem when I clicked to accordeon whole section became biger and background did not match with layout. 
Decided it with using static height for background.

**Comment by DmitroLis** [comment]
The bug was fixed
