### ISSUE TITLE
[FE] [Landing] Incorrect question numbering and text position in the FAQ section.

### ISSUE THREAD

**Issue by OksanaTrokoz** [ratifire/devrate-web#968]
Bug Summary:  Question numbers in the FAQ do not match the design; text shifts downward when expanding an answer.
Steps to reproduce:
1. Open the page with the FAQ section.
2. Compare the question numbers with the design.
3. Click the dropdown button next to any question to expand the answer.

Expected result:
Question numbers are displayed as per the design.
Text in the parallel column remains in place when an answer is expanded.
![Image](https://github.com/user-attachments/assets/fd8d9388-9fe1-47ba-b503-0788056089a8)
![Image](https://github.com/user-attachments/assets/179a7ee9-7c66-4e0f-9087-46000185c435)

Actual result:
Question numbers do not match the design.
When expanding an answer, the text in the parallel column shifts downward.
![Image](https://github.com/user-attachments/assets/ca095f73-82f0-4984-a0b7-675d15a9624f)
![Image](https://github.com/user-attachments/assets/8455e7b3-49d9-4ff7-8ce4-12e68c176aba)
Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 11

**Comment by RuslanSoroka** [comment]
there was a problem with the fact that when opening the spoiler, the scroll was triggered on the content and the beginning of the spoiler rose higher, I solved the problem with window.scrollTo but without smoothness

**Comment by OksanaTrokoz** [comment]
The Bug was fixed
![Снимок экрана 2024-12-04 133809](https://github.com/user-attachments/assets/55ef0183-b8e4-40d6-b60f-7b8e94908ff5)
