### ISSUE TITLE
[FE] [Specialization] Error when deleting a specialization with scheduled interviews.

### ISSUE THREAD

**Issue by OksanaTrokoz** [ratifire/devrate-web#969]
Bug Summary: Error when deleting a specialization with a scheduled interview.
Preconditions:
The user is registered and has a scheduled interview for the specialization Ada.
Steps to Reproduce:
1. Open the "Specializations" page.
2. Find the specialization Ada.
3. Click on the three dots next to the selected specialization.
4. Select the "Delete" option.
Expected result: The specialization Ada is successfully deleted.
Actual Result:
An error window. The specialization Ada is not deleted.
Browser: Chrome 130.0.6723.70 (Official Build) (64-bit))
OS: Windows 11
![Image](https://github.com/user-attachments/assets/9d05fa50-f66b-4eea-a258-e1a320fa16ab)
https://github.com/user-attachments/assets/7dccb6a6-54b8-4dc0-a186-0ff5bca185d5

**Comment by IvashchenkoIvanIgorevich** [comment]
@OksanaTrokoz, thank you. The backend work is complete (https://github.com/ratifire/devrate-service/issues/624). I notified @BhdnS that he will make changes on the frontend side.

**Comment by IrinaTonkonozhenko** [comment]
Bug fixed![Image](https://github.com/user-attachments/assets/e25b8d8e-41ca-4c17-82d7-c6288538746d)
