### ISSUE TITLE
Correct "Contact Information" text for empty profile

### ISSUE THREAD

**Issue by SamZakharov** [ratifire/devrate-web#970]
![Image](https://github.com/user-attachments/assets/2eab2ef2-abcf-408f-9532-fba56160d121)

**Comment by SamZakharov** [comment]
Нужно поменять или добавить текст сообщения для незаполненного личного профиля. Сейчас выводится наверное заглушка из локалей.

**Comment by IrinaTonkonozhenko** [comment]
Verified
