### ISSUE TITLE
[FE] Validation error text overlaps with the "Name" input field.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#983]
**Bug Summary**
The validation error message overlaps with the "Name" input field instead of being displayed below it, causing a misalignment in the UI.

**Steps to Reproduce**

Open the registration form.
Enter an invalid value in the "Name" field (e.g., CBBC2).
Attempt to submit the form.
Observe the position of the validation error message.

**Expected Result**
The validation error message should be displayed below the "Name" field without overlapping or interfering with the input area.

**Actual Result**
The validation error message ("Only uppercase and lowercase letters allowed") overlaps with the "Name" input field, affecting readability and making the form look visually broken.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/5e4f460d-b65c-41b0-9dbc-cff3c4cc27ee)

**Environment**

Browser: Chrome 129.0.6668.90
Operating System: Windows 10

**Comment by DmitroLis** [comment]
The bug was fixed
